export type Committee = {
  id: string;
  slug: string;
  name: string;
  level: string;
  theme: string;
  size: string;
  blurb: string;
  overview: string;
  topic: string;
  difficulty: string;
  format: string;
  chairs: Array<{ name: string; bio: string }>;
  resources: string[];
  backgroundGuide: string;
};

export const committeesPageContent = {
  title: "Committees",
  intro:
    "Our 2026 committees are currently being prepared. Explore the 2025 committees below for a preview.",
  heroImage: {
    src: "/placeholders/committee-1200x800.jpg",
    alt: "Delegates in active committee session",
    note: "delegates in active committee, 3:2, recommended 1200x800",
  },
  continueLabel: "Continue to Conference Program",
  searchLabel: "Search committees",
  searchPlaceholder: "Search by name, topic, format, or difficulty",
  allOptionLabel: "All",
  filterThemeLabel: "Track",
  filterLevelLabel: "Level",
  sizeLabel: "Room Size",
  clearFiltersLabel: "Clear filters",
  openDetailsLabel: "Open dossier",
  noResults: "No committees match your filters.",
  detailBackLabel: "Back to all committees",
  detailCloseLabel: "Close dossier",
  sections: {
    overview: "Overview",
    difficulty: "Difficulty",
    topic: "Topic",
    format: "Format",
    chairs: "Chairs",
    resources: "Resources",
    guide: "Background Guide",
  },
};

const placeholderChairs = [
  { name: "Chair Placeholder", bio: "TODO: Replace with the confirmed 2026 chair biography for this committee." },
  { name: "Vice Chair Placeholder", bio: "TODO: Replace with the confirmed 2026 vice-chair biography for this committee." },
];

const placeholderResources = [
  "TODO: Add confirmed background guide link when the 2026 committee packet is published.",
  "TODO: Add research primer or committee brief when available.",
];

export const committees: Committee[] = [
  {
    id: "sdg-16-un-human-rights-office",
    slug: "sdg-16-un-human-rights-office",
    name: "SDG 16: UN Human Rights Office",
    level: "Intermediate",
    theme: "General Assemblies",
    size: "Double Delegation",
    blurb: "Empowering and Advancing Civil Society.",
    overview: "SSUNS 2025 preview committee from the live programme.",
    topic: "Double Delegation : Empowering and Advancing Civil Society",
    difficulty: "Standard General Assembly experience.",
    format: "General Assembly",
    chairs: placeholderChairs,
    resources: placeholderResources,
    backgroundGuide: "TODO: Add 2026 guide link.",
  },
  {
    id: "sdg-2-fao",
    slug: "sdg-2-fao",
    name: "SDG 2: FAO",
    level: "Intermediate",
    theme: "General Assemblies",
    size: "Double Delegation",
    blurb: "Global Food Security and Economic Stability in Conflict Zones.",
    overview: "SSUNS 2025 preview committee from the live programme.",
    topic: "Double Delegation : Global Food Security and Economic Stability in Conflict Zones",
    difficulty: "Standard General Assembly experience.",
    format: "General Assembly",
    chairs: placeholderChairs,
    resources: placeholderResources,
    backgroundGuide: "TODO: Add 2026 guide link.",
  },
  {
    id: "copus",
    slug: "copus",
    name: "COPUS",
    level: "Intermediate",
    theme: "Economic and Social Councils",
    size: "Medium",
    blurb: "Furthering Space Deweaponization and Promoting an Inclusive and Secure Space.",
    overview: "SSUNS 2025 preview committee from the live programme.",
    topic: "Furthering Space Deweaponization and Promoting an Inclusive and Secure Space",
    difficulty: "Standard Economic and Social Council pacing.",
    format: "ECOSOC",
    chairs: placeholderChairs,
    resources: placeholderResources,
    backgroundGuide: "TODO: Add 2026 guide link.",
  },
  {
    id: "unscear",
    slug: "unscear",
    name: "UNSCEAR",
    level: "Intermediate",
    theme: "Economic and Social Councils",
    size: "Medium",
    blurb: "Addressing Radiation and Nuclear Energy Dangers in Areas of Vulnerability.",
    overview: "SSUNS 2025 preview committee from the live programme.",
    topic: "Addressing Radiation and Nuclear Energy Dangers in Areas of Vulnerability",
    difficulty: "Standard Economic and Social Council pacing.",
    format: "ECOSOC",
    chairs: placeholderChairs,
    resources: placeholderResources,
    backgroundGuide: "TODO: Add 2026 guide link.",
  },
  {
    id: "unpfii",
    slug: "unpfii",
    name: "UNPFII",
    level: "Intermediate",
    theme: "Economic and Social Councils",
    size: "Medium",
    blurb: "Breaking the Cycle: Ensuring Indigenous Autonomy and Promoting First Nations Rights.",
    overview: "SSUNS 2025 preview committee from the live programme.",
    topic: "Breaking the Cycle: Ensuring Indigenous Autonomy and Promoting First Nations Rights",
    difficulty: "Standard Economic and Social Council pacing.",
    format: "ECOSOC",
    chairs: placeholderChairs,
    resources: placeholderResources,
    backgroundGuide: "TODO: Add 2026 guide link.",
  },
  {
    id: "sdg-13",
    slug: "sdg-13",
    name: "SDG 13",
    level: "Intermediate",
    theme: "Economic and Social Councils",
    size: "Medium",
    blurb: "4th International Conference on Small Island Developing States (May 2024, Antigua).",
    overview: "SSUNS 2025 preview committee from the live programme.",
    topic: "4th International Conference on Small Island Developing States (May 2024, Antigua)",
    difficulty: "Standard Economic and Social Council pacing.",
    format: "ECOSOC",
    chairs: placeholderChairs,
    resources: placeholderResources,
    backgroundGuide: "TODO: Add 2026 guide link.",
  },
  {
    id: "icao",
    slug: "icao",
    name: "ICAO",
    level: "Beginner",
    theme: "Economic and Social Councils",
    size: "Medium",
    blurb: "Beginner Committee: Sustainability and Technological Takeoff.",
    overview: "SSUNS 2025 preview committee from the live programme.",
    topic: "Beginner Committee: Sustainability and Technological Takeoff",
    difficulty: "Beginner Committee.",
    format: "ECOSOC",
    chairs: placeholderChairs,
    resources: placeholderResources,
    backgroundGuide: "TODO: Add 2026 guide link.",
  },
  {
    id: "cstd",
    slug: "cstd",
    name: "CSTD",
    level: "Intermediate",
    theme: "Economic and Social Councils",
    size: "Medium",
    blurb: "Cyber Security and Digital Rights.",
    overview: "SSUNS 2025 preview committee from the live programme.",
    topic: "Cyber Security and Digital Rights",
    difficulty: "Standard Economic and Social Council pacing.",
    format: "ECOSOC",
    chairs: placeholderChairs,
    resources: placeholderResources,
    backgroundGuide: "TODO: Add 2026 guide link.",
  },
  {
    id: "this-is-the-remix",
    slug: "this-is-the-remix",
    name: "This is the Remix",
    level: "Intermediate",
    theme: "Specialized Committees",
    size: "Small",
    blurb: "Spotify Board of Directors, 2025.",
    overview: "SSUNS 2025 preview committee from the live programme.",
    topic: "Spotify Board of Directors, 2025",
    difficulty: "Specialized committee pacing.",
    format: "Specialized",
    chairs: placeholderChairs,
    resources: placeholderResources,
    backgroundGuide: "TODO: Add 2026 guide link.",
  },
  {
    id: "fair-play-or-foul-play",
    slug: "fair-play-or-foul-play",
    name: "Fair Play or Foul Play?",
    level: "Intermediate",
    theme: "Specialized Committees",
    size: "Small",
    blurb: "FIFA World Cup Mexico, USA, Canada, 2026.",
    overview: "SSUNS 2025 preview committee from the live programme.",
    topic: "FIFA World Cup Mexico, USA, Canada, 2026",
    difficulty: "Specialized committee pacing.",
    format: "Specialized",
    chairs: placeholderChairs,
    resources: placeholderResources,
    backgroundGuide: "TODO: Add 2026 guide link.",
  },
  {
    id: "a-sticky-situation",
    slug: "a-sticky-situation",
    name: "A Sticky Situation…",
    level: "High Crisis",
    theme: "Specialized Committees",
    size: "Small",
    blurb: "Producteurs et productrices acéricoles du Québec (PPAQ) – The Maple Syrup Cartel.",
    overview: "SSUNS 2025 preview committee from the live programme.",
    topic: "Producteurs et productrices acéricoles du Québec (PPAQ) – The Maple Syrup Cartel",
    difficulty: "High Level of Crisis.",
    format: "Specialized Crisis",
    chairs: placeholderChairs,
    resources: placeholderResources,
    backgroundGuide: "TODO: Add 2026 guide link.",
  },
  {
    id: "a-riveting-endeavour",
    slug: "a-riveting-endeavour",
    name: "A Riveting Endeavour",
    level: "Low Crisis",
    theme: "Specialized Committees",
    size: "Small",
    blurb: "The National Federation of Women Workers – The Fight Beyond the Battlefield, 1917.",
    overview: "SSUNS 2025 preview committee from the live programme.",
    topic: "The National Federation of Women Workers – The Fight Beyond the Battlefield, 1917",
    difficulty: "Low Level of Crisis.",
    format: "Specialized Crisis",
    chairs: placeholderChairs,
    resources: placeholderResources,
    backgroundGuide: "TODO: Add 2026 guide link.",
  },
  {
    id: "sea-it-your-way",
    slug: "sea-it-your-way",
    name: "Sea it your way",
    level: "Low Crisis",
    theme: "Specialized Committees",
    size: "Small",
    blurb: "ICJ: The Chilean-Peruvian Maritime Dispute, 2014.",
    overview: "SSUNS 2025 preview committee from the live programme.",
    topic: "ICJ: The Chilean-Peruvian Maritime Dispute, 2014",
    difficulty: "Low Level of Crisis.",
    format: "Specialized Crisis",
    chairs: placeholderChairs,
    resources: placeholderResources,
    backgroundGuide: "TODO: Add 2026 guide link.",
  },
  {
    id: "pressing-matters",
    slug: "pressing-matters",
    name: "Pressing Matters",
    level: "Low Crisis",
    theme: "Specialized Committees",
    size: "Small",
    blurb: "The Washington Post – Bezos Acquisition, 2013.",
    overview: "SSUNS 2025 preview committee from the live programme.",
    topic: "The Washington Post – Bezos Acquisition, 2013",
    difficulty: "Low Level of Crisis.",
    format: "Specialized Crisis",
    chairs: placeholderChairs,
    resources: placeholderResources,
    backgroundGuide: "TODO: Add 2026 guide link.",
  },
  {
    id: "la-litterature-comme-resistance",
    slug: "la-litterature-comme-resistance",
    name: "La littérature comme résistance",
    level: "Bilingual",
    theme: "Specialized Committees",
    size: "Small",
    blurb: "French Bilingual: Le Salon du Livre Francophone de Beyrouth – Édition 2018.",
    overview: "SSUNS 2025 preview committee from the live programme.",
    topic: "French Bilingual: Le Salon du Livre Francophone de Beyrouth – Édition 2018",
    difficulty: "French Bilingual specialized committee.",
    format: "Specialized",
    chairs: placeholderChairs,
    resources: placeholderResources,
    backgroundGuide: "TODO: Add 2026 guide link.",
  },
  {
    id: "ad-hoc-spec",
    slug: "ad-hoc-spec",
    name: "Ad Hoc Spec",
    level: "TBA",
    theme: "Specialized Committees",
    size: "Small",
    blurb: "Specialized committee to be announced.",
    overview: "SSUNS 2025 preview committee from the live programme.",
    topic: "Ad Hoc Spec",
    difficulty: "To be announced.",
    format: "Specialized",
    chairs: placeholderChairs,
    resources: placeholderResources,
    backgroundGuide: "TODO: Add 2026 guide link.",
  },
  {
    id: "expecto-patronum",
    slug: "expecto-patronum",
    name: "Expecto Patronum",
    level: "Advanced",
    theme: "Crisis Committees",
    size: "Small",
    blurb: "Ministry of Magic and the Return of the Dark Lord.",
    overview: "SSUNS 2025 preview committee from the live programme.",
    topic: "Ministry of Magic and the Return of the Dark Lord",
    difficulty: "Advanced crisis pacing.",
    format: "Crisis",
    chairs: placeholderChairs,
    resources: placeholderResources,
    backgroundGuide: "TODO: Add 2026 guide link.",
  },
  {
    id: "absolute-cinema",
    slug: "absolute-cinema",
    name: "Absolute Cinema",
    level: "Advanced",
    theme: "Crisis Committees",
    size: "Small",
    blurb: "The Cinematographe Lumière Board of Directors, 1897.",
    overview: "SSUNS 2025 preview committee from the live programme.",
    topic: "The Cinematographe Lumière Board of Directors, 1897",
    difficulty: "Advanced crisis pacing.",
    format: "Crisis",
    chairs: placeholderChairs,
    resources: placeholderResources,
    backgroundGuide: "TODO: Add 2026 guide link.",
  },
  {
    id: "a-mughal-game-of-thrones",
    slug: "a-mughal-game-of-thrones",
    name: "A Mughal Game of Thrones",
    level: "Advanced",
    theme: "Crisis Committees",
    size: "Small",
    blurb: "Advanced Committee: The succession of Shah Jahan, 1658.",
    overview: "SSUNS 2025 preview committee from the live programme.",
    topic: "Advanced Committee: The succession of Shah Jahan, 1658",
    difficulty: "Advanced Committee.",
    format: "Crisis",
    chairs: placeholderChairs,
    resources: placeholderResources,
    backgroundGuide: "TODO: Add 2026 guide link.",
  },
  {
    id: "the-pink-panther-strikes-again",
    slug: "the-pink-panther-strikes-again",
    name: "The Pink Panther Strikes Again",
    level: "Advanced",
    theme: "Crisis Committees",
    size: "Small",
    blurb: "The Pink Panther International Jewel Thieves, 2012.",
    overview: "SSUNS 2025 preview committee from the live programme.",
    topic: "The Pink Panther International Jewel Thieves, 2012",
    difficulty: "Advanced crisis pacing.",
    format: "Crisis",
    chairs: placeholderChairs,
    resources: placeholderResources,
    backgroundGuide: "TODO: Add 2026 guide link.",
  },
  {
    id: "vive-la-revolution-americaine",
    slug: "vive-la-revolution-americaine",
    name: "Vive la Révolution… Américaine",
    level: "Advanced",
    theme: "Crisis Committees",
    size: "Small",
    blurb: "The Siege of Quebec 1775.",
    overview: "SSUNS 2025 preview committee from the live programme.",
    topic: "The Siege of Quebec 1775",
    difficulty: "Advanced crisis pacing.",
    format: "Crisis",
    chairs: placeholderChairs,
    resources: placeholderResources,
    backgroundGuide: "TODO: Add 2026 guide link.",
  },
  {
    id: "ad-hoc-of-the-secretary-general",
    slug: "ad-hoc-of-the-secretary-general",
    name: "Ad Hoc of the Secretary-General",
    level: "TBA",
    theme: "Crisis Committees",
    size: "Small",
    blurb: "Ad Hoc crisis committee.",
    overview: "SSUNS 2025 preview committee from the live programme.",
    topic: "Ad Hoc of the Secretary-General",
    difficulty: "To be announced.",
    format: "Crisis",
    chairs: placeholderChairs,
    resources: placeholderResources,
    backgroundGuide: "TODO: Add 2026 guide link.",
  },
  {
    id: "a-fresco-of-fire-and-fortune",
    slug: "a-fresco-of-fire-and-fortune",
    name: "A Fresco of Fire and Fortune",
    level: "Advanced",
    theme: "Joint Crisis Committees",
    size: "Joint Crisis",
    blurb: "The War of Chioggia, 1376 (Republic of Venice vs Republic of Genoa).",
    overview: "SSUNS 2025 preview committee from the live programme.",
    topic: "The War of Chioggia, 1376 (Republic of Venice vs Republic of Genoa)",
    difficulty: "Joint Crisis pacing.",
    format: "Joint Crisis",
    chairs: placeholderChairs,
    resources: placeholderResources,
    backgroundGuide: "TODO: Add 2026 guide link.",
  },
  {
    id: "sip-happens",
    slug: "sip-happens",
    name: "Sip Happens",
    level: "Advanced",
    theme: "Joint Crisis Committees",
    size: "Joint Crisis",
    blurb: "The Cola Wars (Coca-Cola and PepsiCo).",
    overview: "SSUNS 2025 preview committee from the live programme.",
    topic: "The Cola Wars (Coca-Cola and PepsiCo)",
    difficulty: "Joint Crisis pacing.",
    format: "Joint Crisis",
    chairs: placeholderChairs,
    resources: placeholderResources,
    backgroundGuide: "TODO: Add 2026 guide link.",
  },
];

export function getCommitteeBySlug(slug: string) {
  return committees.find((committee) => committee.slug === slug);
}
