export const registrationContent = {
  title: "Registration",
  intro:
    "Registration for SSUNS 2026 will open on April 1st! This year, we are introducing a new registration system designed to improve your experience and streamline the process.",
  sections: {
    flow: "How To Register",
    pathways: "Registration Pathways",
    timeline: "Registration Timeline",
    fees: "Fees & Funding",
    currentTier: "Current registration tier",
    walkthrough: "Munager walkthrough",
    listserv: "List-serv",
  },
  chapters: [
    {
      href: "/registration",
      title: "Information",
      summary: "Registration for SSUNS 2026 opens April 1, 2026.",
      body: [
        "Registration for SSUNS 2026 will open on April 1st!",
        "This year, we are introducing a new registration system designed to improve your experience and streamline the process.",
        "Additional details, including step-by-step instructions and important updates, will be posted here throughout March. We encourage all delegates and advisors to review this information in advance to ensure a smooth registration.",
        "The conference will take place from November 12-15, 2026.",
      ],
    },
    {
      href: "/registration/how-to-register",
      title: "How to Register",
      summary: "Use Munager to complete delegation registration.",
      body: [
        "How to Register.",
        "1. Visit the official SSUNS registration page and review the conference registration instructions.",
        "2. Complete your school’s registration through MUNager using the official conference link.",
        "For a detailed walkthrough of the process, please refer to the MUNager Registration Guide: https://munager.com/apply-guide/.",
        "3. Join the SSUNS listserv to receive important updates and announcements leading up to the conference.",
        "4. Check the registration section of our website for information on fees, deadlines, and policy updates.",
        "If you have any further questions, please contact our Chargée d’Affaires, Costas Oreopoulos, at schools@ssuns.org.",
      ],
    },
    {
      href: "/registration/fees",
      title: "Fees",
      summary: "SSUNS 2026 registration fees and dates.",
      body: [
        "SSUNS 2026 Registration Fees and Dates.",
        "*All prices are in CAD **Tax are not included.",
        "The Delegate Fee applies to each delegate who wishes to register. The Delegation Fee is an additional one time fee that covers the entire delegation.",
        "Registration opens: April 1st.",
        "Registration closes: October 16 or upon reaching capacity.",
      ],
    },
    {
      href: "/registration/financial-aid",
      title: "Financial Aid",
      summary: "Support information for financial accessibility.",
      body: [
        "Financial Policies and Aid will be updated soon!",
        "Financial Aid Application Deadlines.",
        "Early: June 8th.",
        "Regular: September 8th.",
        "Final Round: October 16th.",
        "Invoice Deadlines.",
        "Early: June 22nd.",
        "Regular: September 16th.",
        "Final Round: October 23rd.",
      ],
    },
    {
      href: "/registration/deadlines",
      title: "Deadlines",
      summary: "Track release dates, registration openings, and conference dates.",
      body: [
        "Registration opens: April 1st.",
        "Registration closes: October 16 or upon reaching capacity.",
        "Financial Aid Application Deadlines: June 8th, September 8th, and October 16th.",
        "Invoice Deadlines: June 22nd, September 16th, and October 23rd.",
      ],
    },
  ],
  steps: [
    "Visit the official SSUNS registration page and review the conference registration instructions.",
    "Complete your school’s registration through MUNager using the official conference link.",
    "Join the SSUNS listserv to receive important updates and announcements leading up to the conference.",
    "Check the registration section of our website for information on fees, deadlines, and policy updates.",
  ],
  timeline: [
    { label: "April 1, 2026", text: "Registration opens." },
    { label: "October 16, 2026", text: "Registration closes or earlier upon reaching capacity." },
    { label: "November 12-15, 2026", text: "Conference dates in Montreal." },
  ],
  currentTier: {
    label: "Registration opens April 1st",
    detail: "The conference will take place from November 12-15, 2026.",
  },
  pricingTimeline: [
    {
      id: "early",
      label: "Early",
      start: "2026-04-01",
      end: "2026-06-01",
      delegationFee: "$110",
      delegateFee: "$120",
    },
    {
      id: "regular",
      label: "Regular",
      start: "2026-06-02",
      end: "2026-09-01",
      delegationFee: "$120",
      delegateFee: "$130",
    },
    {
      id: "final",
      label: "Final",
      start: "2026-09-02",
      end: "2026-10-16",
      delegationFee: "$130",
      delegateFee: "$145",
    },
  ],
  pricingTimelineText: {
    title: "Registration timeline",
    delegationFee: "Delegation fee",
    delegateFee: "Per delegate",
    current: "Current",
    financialAidDeadlines: "Financial aid deadlines",
    to: "to",
  },
  financialAidDeadlines: ["June 8", "September 8", "October 16"],
  feePlaceholders: [
    { title: "Fees", body: "The Delegate Fee applies to each delegate who wishes to register. The Delegation Fee is an additional one time fee that covers the entire delegation." },
    { title: "Policies", body: "Additional information, including policy updates, will continue to be posted here." },
    { title: "Financial Aid", body: "Financial Policies and Aid will be updated soon." },
  ],
  tracks: [
    {
      title: "Munager Registration",
      body: "Munager is the single registration platform used for SSUNS 2026.",
      href: "/registration/how-to-register",
    },
    {
      title: "Delegate Handbook",
      body: "The Delegate Handbook, containing key information on conference policies, preparation, and procedures, will be released prior to the conference.",
      href: "/resources/handbook",
    },
    {
      title: "Financial Aid Window",
      body: "Financial aid details and supporting policies will be linked from the financial aid chapter once published.",
      href: "/registration/financial-aid",
    },
  ],
  listserv: {
    label: "Stay updated",
    body: "You can now subscribe to receive SSUNS weekly e-mails! Keep up with our latest updates, registration information and much more!",
    href: "https://www.ssuns.org/registration-information",
  },
  listservForm: {
    nameLabel: "Name",
    emailLabel: "Email",
    schoolLabel: "School",
    submitLabel: "Join listserv",
    successLabel: "Thanks. Your information has been submitted.",
    fallbackLabel: "Unable to submit automatically. Please email schools@ssuns.org.",
  },
  letter: {
    label: "Chargée d’Affaires",
    title: "A letter to schools",
    body: [
      "Sign up with your email address to receive SSUNS 2026 latest news from our Chargée d’Affaires.",
      "Be sure to sign up to our list-serv below to stay updated as information is released throughout March.",
    ],
    signature: "Costas Oreopoulos",
    role: "Chargée d’Affaires, SSUNS 2026",
  },
  cta: { label: "Register now", href: "https://www.munager.com/user/newApplication/SSUNS2026" },
  munagerVideo: {
    src: "/video/munager-howto.mp4",
    poster: "/placeholders/hero-1920x1080.jpg",
    fallbackSrc: "/video/ssuns-recap-2025.mp4",
    title: "Munager walkthrough",
    unavailableLabel: "Video coming soon",
    note: "screen capture of Munager registration flow, 16:9, recommended 1920x1080",
  },
  image: {
    src: "/headshots/costas.jpg",
    alt: "Portrait placeholder for the registration office",
    note: "delegate registration portrait, 4:5, recommended 800x1000",
  },
};
