export const registrationContent = {
  title: "Registration",
  intro:
    "Registration for SSUNS 2026 will open on April 1st! This year, we are introducing a new registration system designed to improve your experience and streamline the process.",
  sections: {
    flow: "How To Register",
    pathways: "Registration Pathways",
    timeline: "Registration Timeline",
    fees: "Fees & Funding",
    currentTier: "Current registration tier",
    walkthrough: "Munager walkthrough",
    listserv: "List-serv",
  },
  chapters: [
    {
      href: "/registration",
      title: "Information",
      summary: "Registration for SSUNS 2026 opens April 1, 2026.",
      body: [
        "Registration for SSUNS 2026 will open on April 1st!",
        "This year, we are introducing a new registration system designed to improve your experience and streamline the process.",
        "Additional details, including step-by-step instructions and important updates, will be posted here throughout March. We encourage all delegates and advisors to review this information in advance to ensure a smooth registration.",
        "The conference will take place from November 12-15, 2026.",
        "Registration opens: April 1st.",
        "Registration closes: October 16 or upon reaching capacity.",
      ],
    },
    {
      href: "/registration/how-to-register",
      title: "How to Register",
      summary: "Use Munager to complete delegation registration.",
      body: ["A step-by-step guide to registering your delegation, managing attendees, and securing committee assignments."],
    },
    {
      href: "/registration/fees",
      title: "Fees",
      summary: "SSUNS 2026 registration fees and dates.",
      body: [
        "SSUNS 2026 Registration Fees and Dates.",
        "*All prices are in CAD **Tax are not included.",
        "The Delegate Fee applies to each delegate who wishes to register. The Delegation Fee is an additional one time fee that covers the entire delegation.",
        "Registration opens: April 1st.",
        "Registration closes: October 16 or upon reaching capacity.",
      ],
    },
    {
      href: "/registration/financial-aid",
      title: "Financial Aid",
      summary: "Support information for financial accessibility.",
      body: [
        "Financial Policies and Aid will be updated soon!",
        "Financial Aid Application Deadlines.",
        "Early: June 8th.",
        "Regular: September 8th.",
        "Final Round: October 16th.",
        "Invoice Deadlines.",
        "Early: June 22nd.",
        "Regular: September 16th.",
        "Final Round: October 23rd.",
      ],
    },
    {
      href: "/registration/deadlines",
      title: "Deadlines",
      summary: "Track release dates, registration openings, and conference dates.",
      body: [
        "Registration opens: April 1st.",
        "Registration closes: October 16 or upon reaching capacity.",
        "Financial Aid Application Deadlines: June 8th, September 8th, and October 16th.",
        "Invoice Deadlines: June 22nd, September 16th, and October 23rd.",
      ],
    },
  ],
  steps: [
    "Visit the official SSUNS registration page and review the conference registration instructions.",
    "Complete your school’s registration through MUNager using the official conference link.",
    "Join the SSUNS listserv to receive important updates and announcements leading up to the conference.",
    "Check the registration section of our website for information on fees, deadlines, and policy updates.",
  ],
  howToGuide: {
    title: "How to Apply",
    overviewHeading: "Overview",
    intro: "A step-by-step guide to registering your delegation, managing attendees, and securing committee assignments.",
    courtesy: "Courtesy of MUNager",
    closing: "Guide content courtesy of MUNager.",
    openGuideLabel: "Open the MUNager apply guide",
    phases: [
      {
        id: "phase1",
        number: 1,
        title: "Phase 1: Submitting Your Application",
        videoId: "PrCFLMbu7Ug",
        steps: [
          { title: "Create an Account", description: "Use the conference link to sign in or register." },
          { title: "Fill School Details", description: "Input name and street address." },
          { title: "Set Your Numbers", description: "Input total Delegates and Faculty Advisors." },
          { title: "Logistics", description: "Answer questions regarding application type, hotels, and visas." },
          { title: "Submit", description: 'Consent to emails and click "Submit Application."' },
        ],
      },
      {
        id: "phase2",
        number: 2,
        title: "Phase 2: Adding Attendees",
        videoId: "awAjt0Lnysk",
        steps: [
          { title: "Navigate", description: 'Go to the "Delegates" tab on the dashboard.' },
          { title: "Input Names", description: 'Click "New Delegate" to add names and emails.' },
          { title: "Assign Roles", description: "Designate Head Delegates where applicable." },
          { title: "Faculty & Policies", description: "Repeat for Faculty Advisors and upload required policy forms." },
        ],
      },
      {
        id: "phase3",
        number: 3,
        title: "Phase 3: Submitting Preferences",
        videoId: "AMVFFxxtj_Y",
        steps: [
          { title: "Open Preferences", description: 'Navigate to the "Preferences" tab.' },
          { title: "Rank Committees", description: "Drag and drop committees into your preferred order." },
          { title: "Select Countries", description: "Search and add 5–15 countries you wish to represent." },
          { title: "Add Notes", description: "Use the text box for any specific requests." },
          { title: "Auto-Save", description: 'Confirm that the "All changes saved" indicator appears.' },
        ],
      },
      {
        id: "phase4",
        number: 4,
        title: "Phase 4: Assigning Delegates",
        videoId: "SxczU3Nkbxw",
        steps: [
          { title: "Committee Assignments", description: 'Navigate to the "Committee Assignments" tab.' },
          { title: "View Roles", description: "See the countries/committees assigned by the conference." },
          { title: "Match Names", description: "Select a delegate from the dropdown for each assignment." },
          { title: "Double Delegations", description: "Ensure both delegate slots are filled for GA/Double Del committees." },
          { title: "Finalize", description: "Confirm assignments are saved (no submit button required)." },
        ],
      },
    ],
  },
  timeline: [
    { label: "April 1, 2026", text: "Registration opens." },
    { label: "October 16, 2026", text: "Registration closes or earlier upon reaching capacity." },
    { label: "November 12-15, 2026", text: "Conference dates in Montreal." },
  ],
  currentTier: {
    label: "Registration opens April 1st",
    detail: "Registration closes October 16 or upon reaching capacity. The conference will take place from November 12-15, 2026.",
  },
  pricingTimeline: [
    {
      id: "early",
      label: "Early",
      start: "2026-04-01",
      end: "2026-06-01",
      delegationFee: "$110",
      delegateFee: "$120",
    },
    {
      id: "regular",
      label: "Regular",
      start: "2026-06-02",
      end: "2026-09-01",
      delegationFee: "$120",
      delegateFee: "$130",
    },
    {
      id: "final",
      label: "Final",
      start: "2026-09-02",
      end: "2026-10-16",
      delegationFee: "$130",
      delegateFee: "$145",
    },
  ],
  pricingTimelineText: {
    title: "Registration timeline",
    delegationFee: "Delegation fee",
    delegateFee: "Per delegate",
    current: "Current",
    financialAidDeadlines: "Financial aid deadlines",
    to: "to",
  },
  financialAidDeadlines: ["June 8", "September 8", "October 16"],
  invoiceDeadlines: ["June 22", "September 16", "October 23"],
  feePlaceholders: [
    { title: "Fees", body: "The Delegate Fee applies to each delegate who wishes to register. The Delegation Fee is an additional one time fee that covers the entire delegation." },
    { title: "Dates", body: "Registration opens: April 1st. Registration closes: October 16 or upon reaching capacity." },
    { title: "Financial Aid", body: "Financial Policies and Aid will be updated soon." },
  ],
  tracks: [
    {
      title: "Munager Registration",
      body: "Munager is the single registration platform used for SSUNS 2026.",
      href: "/registration/how-to-register",
    },
    {
      title: "Delegate Handbook",
      body: "The Delegate Handbook, containing key information on conference policies, preparation, and procedures, will be released prior to the conference.",
      href: "/resources/handbook",
    },
    {
      title: "Financial Aid Window",
      body: "Financial aid details and supporting policies will be linked from the financial aid chapter once published.",
      href: "/registration/financial-aid",
    },
  ],
  listserv: {
    label: "Stay updated",
    body: "You can now subscribe to receive SSUNS weekly e-mails! Keep up with our latest updates, registration information and much more!",
    href: "https://www.ssuns.org/registration-information",
  },
  listservForm: {
    nameLabel: "Name",
    emailLabel: "Email",
    schoolLabel: "School",
    submitLabel: "Join listserv",
    successLabel: "Thanks. Your information has been submitted.",
    fallbackLabel: "Unable to submit automatically. Please email schools@ssuns.org.",
  },
  letter: {
    label: "Chargée d’Affaires",
    title: "A message from the Chargé d'affaires",
    body: [
      "Dear SSUNS Delegates and Faculty Advisors,",
      "My name is Costas Oreopoulos and it is my distinct privilege to serve as your Chargé d’Affaires for SSUNS 2026. Since its debut in 1993, SSUNS has grown to be Canada’s premier Model United Nations conference. Now in its 34th edition, we continue to provide a world-class conference experience for high school and CEGEP students. Each November, over 1400 students from around the globe join us for four days of dynamic committee sessions, captivating debate and immersive simulations.",
      "Beyond committee sessions, SSUNS offers a range of opportunities to enrich your experience, including workshops, social events and guided tours of McGill University. Faculty Advisors will have the chance to observe their delegates in action, connect with fellow educators and enjoy the Faculty Advisor Lounge and social events. All of this takes place in the beautifully vibrant city of Montreal, where attendees can explore iconic landmarks and experience its unique culture.",
      "Whether you are returning to SSUNS or joining us for the first time, we are incredibly excited to welcome you for an unforgettable weekend of diplomacy, debate and collaboration. I look forward to seeing you all this November!",
      "Sign up with your email address to receive SSUNS 2026 latest news from our Chargée d’Affaires.",
    ],
    signature: "Costas Oreopoulos",
    role: "Chargée d’Affaires, SSUNS 2026",
  },
  cta: { label: "Register now", href: "https://www.munager.com/user/newApplication/SSUNS2026" },
  munagerVideo: {
    src: "/video/munager-howto.mp4",
    poster: "/pictures/hero-1920x1080.jpg",
    fallbackSrc: "/video/ssuns-recap-2025.mp4",
    title: "Munager walkthrough",
    unavailableLabel: "Video coming soon",
    note: "screen capture of Munager registration flow, 16:9, recommended 1920x1080",
  },
  image: {
    src: "/headshots/costas.jpg",
    alt: "Portrait placeholder for the registration office",
    note: "delegate registration portrait, 4:5, recommended 800x1000",
  },
};
